export default function TestLegs() {
  return (
    <g g transform="translate(50, 200)">
      <g transform="translate(0, -10)">
        <g transform="translate(-5,0)">
          <path
            d="M40,0 C0,53 65,98 12,154"
            stroke="black"
            strokeWidth="10"
            fill="transparent"
          />
          <circle cx="12.5" cy="153" r="5" fill="black" />
        </g>
        <g transform="translate(10,0) rotate(5)">
          <path
            d="M40,0 C0,53 65,98 12,154"
            stroke="black"
            strokeWidth="10"
            fill="transparent"
          />
          <circle cx="12.5" cy="153" r="5" fill="black" />
        </g>
        <g transform="translate(2 ,-5) rotate(0)">
          <path
            d="M40,0 C0,53 65,98 12,154"
            stroke="black"
            strokeWidth="11"
            fill="transparent"
          />
          <circle cx="12.5" cy="153" r="5" fill="black" />
        </g>
        <g>
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(2, -15)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(7.5, 23) scale(.8)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(10, 35) scale(.75)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(12, 44) scale(.75)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(15, 55) scale(.7)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(15, 65) scale(.7)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(17, 80) scale(.6)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(19, 93) scale(.5)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(17, 100) scale(.5)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(14, 107) scale(.5)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(14, 118) scale(.4)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
      </g>
      <g transform="translate(32,-10)">
        <g transform="translate(-5,0)">
          <path
            d="M40,0 C0,53 65,98 12,154"
            stroke="black"
            strokeWidth="10"
            fill="transparent"
          />
          <circle cx="12.5" cy="153" r="5" fill="black" />
        </g>
        <g transform="translate(10,0) rotate(5)">
          <path
            d="M40,0 C0,53 65,98 12,154"
            stroke="black"
            strokeWidth="10"
            fill="transparent"
          />
          <circle cx="12.5" cy="153" r="5" fill="black" />
        </g>
        <g transform="translate(2 ,-5) rotate(0)">
          <path
            d="M40,0 C0,53 65,98 12,154"
            stroke="black"
            strokeWidth="11"
            fill="transparent"
          />
          <circle cx="12.5" cy="153" r="5" fill="black" />
        </g>
        <g>
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(2, -15)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(7.5, 23) scale(.8)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(10, 35) scale(.75)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(12, 44) scale(.75)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(15, 55) scale(.7)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(15, 65) scale(.7)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(17, 80) scale(.6)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(19, 93) scale(.5)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(17, 100) scale(.5)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(14, 107) scale(.5)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
        <g transform="translate(14, 118) scale(.4)">
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="white"
            strokeWidth="4"
            fill="transparent"
          />
          <circle
            cx="30"
            cy="50"
            r="3"
            stroke="#C3E8BD"
            strokeWidth="2"
            fill="transparent"
          />
        </g>
      </g>
    </g>
  );
}
