export default function TripodLegs() {
  return (
    <g transform="translate(50, 200)">
      <g transform="translate(0, -10)">
        <g transform="translate(10, -10)">
          <rect
            x="20"
            y="0"
            height="150"
            width="15"
            transform="rotate(15)"
            fill="#ffadad"
          />
        </g>
        <g>
          <rect x="43" y="0" height="150" width="15" fill="#ffadad" />
          <g transform="translate(10, 12.5)">
            <rect
              x="50"
              y="0"
              height="150"
              width="15"
              transform="rotate(-15)"
              fill="#ffadad"
            />
          </g>
          <circle cx="17" cy="70" r="5" fill="yellow" />
          <circle cx="50" cy="77" r="5" fill="yellow" />
          <circle cx="85" cy="70" r="5" fill="yellow" />
          <g transform="rotate(10) translate(24, 0)">
            <rect
              x="-24"
              y="125"
              rx="10"
              ry="10"
              width="34"
              height="17"
              fill="#00b4d8"
              transform="scale(1.15) translate(0, -18)"
            />
            <rect
              x="-10"
              y="108"
              rx="5"
              ry="5"
              width="20"
              height="29"
              fill="#00b4d8"
              transform="scale(1.2) translate(0, -18)"
            />

            <rect
              x="-25"
              y="125"
              rx="10"
              ry="10"
              width="35"
              height="15"
              fill="#ffd6a5"
            />
            <rect
              x="-10"
              y="110"
              rx="5"
              ry="5"
              width="20"
              height="30"
              fill="#ffd6a5"
            />
            <circle
              cx="-3"
              cy="115"
              r="1.5"
              stroke="#00b4d8"
              strokeWidth="2px"
              fill="transparent"
            />
            <circle
              cx="-3.5"
              cy="120"
              r="1.5"
              stroke="#00b4d8"
              strokeWidth="2px"
              fill="transparent"
            />
            <circle
              cx="-4"
              cy="125"
              r="1.5"
              stroke="#00b4d8"
              strokeWidth="2px"
              fill="transparent"
            />
            <line
              x1="-10"
              x2="-3"
              y1="115"
              y2="115"
              stroke="#00b4d8"
              strokeWidth="2px"
            />
            <line
              x1="-10"
              x2="-3.5"
              y1="120"
              y2="120"
              stroke="#00b4d8"
              strokeWidth="2px"
            />
            <line
              x1="-12"
              x2="-4"
              y1="124"
              y2="125"
              stroke="#00b4d8"
              strokeWidth="2px"
            />
          </g>
          <g transform="rotate(0) translate(50, 15)">
            <rect
              x="-24"
              y="125"
              rx="10"
              ry="10"
              width="34"
              height="17"
              fill="#00b4d8"
              transform="scale(1.15) translate(0, -18)"
            />
            <rect
              x="-10"
              y="108"
              rx="5"
              ry="5"
              width="20"
              height="29"
              fill="#00b4d8"
              transform="scale(1.2) translate(0, -18)"
            />

            <rect
              x="-25"
              y="125"
              rx="10"
              ry="10"
              width="35"
              height="15"
              fill="#ffd6a5"
            />
            <rect
              x="-10"
              y="110"
              rx="5"
              ry="5"
              width="20"
              height="30"
              fill="#ffd6a5"
            />
            <circle
              cx="-3"
              cy="115"
              r="1.5"
              stroke="#00b4d8"
              strokeWidth="2px"
              fill="transparent"
            />
            <circle
              cx="-3.5"
              cy="120"
              r="1.5"
              stroke="#00b4d8"
              strokeWidth="2px"
              fill="transparent"
            />
            <circle
              cx="-4"
              cy="125"
              r="1.5"
              stroke="#00b4d8"
              strokeWidth="2px"
              fill="transparent"
            />
            <line
              x1="-10"
              x2="-3"
              y1="115"
              y2="115"
              stroke="#00b4d8"
              strokeWidth="2px"
            />
            <line
              x1="-10"
              x2="-3.5"
              y1="120"
              y2="120"
              stroke="#00b4d8"
              strokeWidth="2px"
            />
            <line
              x1="-12"
              x2="-4"
              y1="124"
              y2="125"
              stroke="#00b4d8"
              strokeWidth="2px"
            />
          </g>
          <g transform="rotate(-12) translate(72, 24)">
            <rect
              x="-24"
              y="125"
              rx="10"
              ry="10"
              width="34"
              height="17"
              fill="#00b4d8"
              transform="scale(1.15) translate(0, -18)"
            />
            <rect
              x="-10"
              y="108"
              rx="5"
              ry="5"
              width="20"
              height="29"
              fill="#00b4d8"
              transform="scale(1.2) translate(0, -18)"
            />

            <rect
              x="-25"
              y="125"
              rx="10"
              ry="10"
              width="35"
              height="15"
              fill="#ffd6a5"
            />
            <rect
              x="-10"
              y="110"
              rx="5"
              ry="5"
              width="20"
              height="30"
              fill="#ffd6a5"
            />
            <circle
              cx="-3"
              cy="115"
              r="1.5"
              stroke="#00b4d8"
              strokeWidth="2px"
              fill="transparent"
            />
            <circle
              cx="-3.5"
              cy="120"
              r="1.5"
              stroke="#00b4d8"
              strokeWidth="2px"
              fill="transparent"
            />
            <circle
              cx="-4"
              cy="125"
              r="1.5"
              stroke="#00b4d8"
              strokeWidth="2px"
              fill="transparent"
            />
            <line
              x1="-10"
              x2="-3"
              y1="115"
              y2="115"
              stroke="#00b4d8"
              strokeWidth="2px"
            />
            <line
              x1="-10"
              x2="-3.5"
              y1="120"
              y2="120"
              stroke="#00b4d8"
              strokeWidth="2px"
            />
            <line
              x1="-12"
              x2="-4"
              y1="124"
              y2="125"
              stroke="#00b4d8"
              strokeWidth="2px"
            />
          </g>
        </g>
      </g>
    </g>
  );
}
