export default function TestBody() {
  return (
    <g transform="translate(50, 85)">
      <circle
        cx="9"
        cy="105"
        r="8"
        fill="#B7C8B5"
        stroke="black"
        strokeWidth="1.5"
      />
      <circle
        cx="91"
        cy="105"
        r="8"
        fill="#B7C8B5"
        stroke="black"
        strokeWidth="1.5"
      />
      <rect
        x="2.5"
        y="3"
        rx="10"
        ry="10"
        width="25"
        height="100"
        stroke="black"
        fill="#909580"
        strokeWidth="1.5"
      />
      <rect
        x="74.5"
        y="3"
        rx="10"
        ry="10"
        width="25"
        height="100"
        stroke="black"
        fill="#909580"
        strokeWidth="1.5"
      />
      <rect
        x="12.5"
        y="1"
        rx="10"
        ry="10"
        width="75"
        height="120"
        stroke="black"
        fill="#909580"
        strokeWidth="1.5"
      />
    </g>
  );
}
